<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-SARCICC" name="com.w2a.suite.admin.testcases.InvalidAdminLoginTest" tests="2" failures="2" timestamp="30 Jan 2019 17:05:55 GMT" time="222.590" errors="0">
  <testcase name="invalidAdminLoginTest" time="81.427" classname="com.w2a.suite.admin.testcases.InvalidAdminLoginTest">
    <failure type="java.lang.AssertionError" message="Failing while typing in an ElementemailField_NAME">
      <![CDATA[java.lang.AssertionError: Failing while typing in an ElementemailField_NAME
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.datadriven.base.TestBase.reportFailure(TestBase.java:215)
at com.w2a.datadriven.base.TestBase.type(TestBase.java:265)
at com.w2a.suite.admin.testcases.InvalidAdminLoginTest.invalidAdminLoginTest(InvalidAdminLoginTest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- invalidAdminLoginTest -->
  <testcase name="invalidAdminLoginTest" time="141.163" classname="com.w2a.suite.admin.testcases.InvalidAdminLoginTest">
    <failure type="java.lang.AssertionError" message="Failing while typing in an ElementemailField_NAME">
      <![CDATA[java.lang.AssertionError: Failing while typing in an ElementemailField_NAME
at org.testng.Assert.fail(Assert.java:96)
at com.w2a.datadriven.base.TestBase.reportFailure(TestBase.java:215)
at com.w2a.datadriven.base.TestBase.type(TestBase.java:265)
at com.w2a.suite.admin.testcases.InvalidAdminLoginTest.invalidAdminLoginTest(InvalidAdminLoginTest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- invalidAdminLoginTest -->
</testsuite> <!-- com.w2a.suite.admin.testcases.InvalidAdminLoginTest -->
